name: DoiCoin
main: Ki\Main
author: của ông nào trên youtube á không nhớ nữa
api: 4.0.0
version: 1.0

commands:
 doixu:
  description: "Đổi Coin từ money và ngược lại "
  permission: doixu.command
  
permissions:
  doixu.command:
    default: true
  
